#!/usr/bin/env python3
# -*- coding: utf-8 -*-

description = """ Extract physiological log files from encoded "_PHYSIO" DICOM file
    generated by CMRR MB sequences """

try:
    import pypandoc
    long_description = pypandoc.convert('README.md', 'rst')
except(IOError, ImportError):
    long_description = open('README.md').read()

from setuptools import setup

DISTNAME = "cmrr2log"
DESCRIPTION = description
VERSION = "0.0.1"
AUTHOR = "CoAxLab"
AUTHOR_EMAIL = "jrasero.daparte@gmail.com"
URL = "https://github.com/CoAxLab/Cmrr2Log"
DOWNLOAD_URL = URL + "/archive/" + VERSION + ".tar.gz"
ENTRY_POINTS = {
    "console_scripts": [
            "cmrr2log = cmrr2log.cmrr2log:main"],
}



if __name__ == "__main__":
    setup(
            name=DISTNAME,
            version=VERSION,
            description=description,
            long_description=long_description,
            author=AUTHOR,
            author_email=AUTHOR_EMAIL,
            url=URL,
            download_url=DOWNLOAD_URL,
            packages=['cmrr2log'],
            entry_points= ENTRY_POINTS,
            install_requires=['future>=0.16.0', 'pydicom>=1.3.0']
            )
